---
AWSTemplateFormatVersion: 2010-09-09
Description: This cloud formation is to deploy rds

Parameters:

  pscgroupname:
    Description: Sec group for ec2
    Type: String
  
  pvpcId:
    Description: vpc ID
    Type: String

  pUsername:
    Description: User RDS
    Type: String

  pPassword:
    Description: Password RDS
    Type: String

  psubnetId:
    Description: subnet ID
    Type: String

Resources:

  rSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 security group
      GroupName: !Ref pscgroupname
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          IpProtocol: "-1"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
      VpcId: !Ref pvpcId
  
  rDBsec:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress: 
        - EC2SecurityGroupId: !Ref rSecGroup
      EC2VpcId: !Ref pvpcId
      GroupDescription: Prueba RDS

  AuroraDBCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties: 
      BackupRetentionPeriod: 7
      DBClusterIdentifier: cluster-4
      DatabaseName: mydb
      DBSubnetGroupName: !Ref psubnetId
      EnableIAMDatabaseAuthentication: false
      ManageMasterUserPassword: false
      DeletionProtection: false
      Engine: aurora-mysql
      EngineMode: 'provisioned'
      MasterUsername: !Ref pUsername
      MasterUserPassword: !Ref pPassword
      Port: 3306
      NetworkType: IPV4
      StorageEncrypted: false
      VpcSecurityGroupIds: 
      - !Ref rSecGroup
  rRDS:
    DependsOn: [AuroraDBCluster]
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.medium
      DBInstanceIdentifier: database-1
      DBClusterIdentifier: !Ref AuroraDBCluster
      EnablePerformanceInsights: false
      Engine: aurora-mysql
      MultiAZ: false
      PubliclyAccessible: true
      UseDefaultProcessorFeatures: true

  rRDSread:
    DependsOn: [AuroraDBCluster]
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.medium
      DBInstanceIdentifier: database-2
      DBClusterIdentifier: !Ref AuroraDBCluster
      EnablePerformanceInsights: false
      Engine: aurora-mysql
      MultiAZ: false
      PubliclyAccessible: true
      UseDefaultProcessorFeatures: true