---
AWSTemplateFormatVersion: 2010-09-09
Description: This cloud formation is to deploy a basic efs

Resources:
  rps:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text 
      Name: pruebaCFL
      Tier: Standard
      Type: String
      Value: nombrebucketprueba

